const expenses= [
    {
        where:"Ravi",
        howMuch:"55",
        when:"12/12/20",
        method:"online"
    },
    {
        where:"Ravi",
        howMuch:"55",
        when:"12/12/20",
        method:"online"
    },    
    {
        where:"Ravi",
        howMuch:"55",
        when:"12/12/20",
        method:"online"
    },    
    {
        where:"Ravi",
        howMuch:"55",
        when:"12/12/20",
        method:"online"
    },    
    {
        where:"Ravi",
        howMuch:"55",
        when:"12/12/20",
        method:"online"
    },    
    {
        where:"Ravi",
        howMuch:"55",
        when:"12/12/20",
        method:"online"
    },    
    {
        where:"Ravi",
        howMuch:"55",
        when:"12/12/20",
        method:"online"
    },
    {
        where:"Ravi",
        howMuch:"55",
        when:"12/12/20",
        method:"online"
    },
    {
        where:"Ravi",
        howMuch:"55",
        when:"12/12/20",
        method:"online"
    },    
    {
        where:"Ravi",
        howMuch:"55",
        when:"12/12/20",
        method:"online"
    },    
    {
        where:"Ravi",
        howMuch:"55",
        when:"12/12/20",
        method:"online"
    },    
    {
        where:"Ravi",
        howMuch:"55",
        when:"12/12/20",
        method:"online"
    },    
    {
        where:"Ravi",
        howMuch:"55",
        when:"12/12/20",
        method:"online"
    },    
    {
        where:"Ravi",
        howMuch:"55",
        when:"12/12/20",
        method:"online"
    },
    {
        where:"Ravi",
        howMuch:"55",
        when:"12/12/20",
        method:"online"
    },
    {
        where:"Ravi",
        howMuch:"55",
        when:"12/12/20",
        method:"online"
    },    
    {
        where:"Ravi",
        howMuch:"55",
        when:"12/12/20",
        method:"online"
    },    
    {
        where:"Ravi",
        howMuch:"55",
        when:"12/12/20",
        method:"online"
    },    
    {
        where:"Ravi",
        howMuch:"55",
        when:"12/12/20",
        method:"online"
    },    
    {
        where:"Ravi",
        howMuch:"55",
        when:"12/12/20",
        method:"online"
    },    
    {
        where:"Ravi",
        howMuch:"55",
        when:"12/12/20",
        method:"online"
    }
]

export default expenses;