const expenses= [
    {
        where:"ravi",
        howMuch:"55",
        when:"12/12/20"
    },
    {
        where:"ravi",
        howMuch:"55",
        when:"12/12/20"
    },    
    {
        where:"ravi",
        howMuch:"55",
        when:"12/12/20"
    },    
    {
        where:"ravi",
        howMuch:"55",
        when:"12/12/20"
    },    
    {
        where:"ravi",
        howMuch:"55",
        when:"12/12/20"
    },    
    {
        where:"ravi",
        howMuch:"55",
        when:"12/12/20"
    },    
    {
        where:"ravi",
        howMuch:"55",
        when:"12/12/20"
    },
    {
        where:"ravi",
        howMuch:"55",
        when:"12/12/20"
    },
    {
        where:"ravi",
        howMuch:"55",
        when:"12/12/20"
    },    
    {
        where:"ravi",
        howMuch:"55",
        when:"12/12/20"
    },    
    {
        where:"ravi",
        howMuch:"55",
        when:"12/12/20"
    },    
    {
        where:"ravi",
        howMuch:"55",
        when:"12/12/20"
    },    
    {
        where:"ravi",
        howMuch:"55",
        when:"12/12/20"
    },    
    {
        where:"ravi",
        howMuch:"55",
        when:"12/12/20"
    },
    {
        where:"ravi",
        howMuch:"55",
        when:"12/12/20"
    },
    {
        where:"ravi",
        howMuch:"55",
        when:"12/12/20"
    },    
    {
        where:"ravi",
        howMuch:"55",
        when:"12/12/20"
    },    
    {
        where:"ravi",
        howMuch:"55",
        when:"12/12/20"
    },    
    {
        where:"ravi",
        howMuch:"55",
        when:"12/12/20"
    },    
    {
        where:"ravi",
        howMuch:"55",
        when:"12/12/20"
    },    
    {
        where:"ravi",
        howMuch:"55",
        when:"12/12/20"
    }
]

export default expenses;